name: early_detection_tb
description: Early TB Detection System - Legacy Enterprise Style
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  intl: ^0.18.1
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256

msix_config:
  display_name: Early TB Detection
  publisher_display_name: Avani Shahane
  identity_name: com.avanishahane.earlytbdetection
  msix_version: 2.0.0.0
  logo_path: assets\images\logo.png
  capabilities: internetClient
